// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CppMate
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "969c8e63-189f-4be0-a8e0-e10bce3cdcef";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string guidCppMatePackageCmdSetString = "f80f8d3c-bf68-4920-aade-1773c0cc052a";
        public static Guid guidCppMatePackageCmdSet = new Guid(guidCppMatePackageCmdSetString);

        public const string guidImagesString = "6568f315-d470-458a-9b18-cec10eaeee2f";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CppMateToolWindowCommandId = 0x0100;
        public const int cmdidAddFolderCmd = 0x1021;
        public const int cmdidAddSourceFile = 0x1022;
        public const int cmdidCppMateStartCommand = 0x1022;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}